# Generated by Django 5.0 on 2023-12-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
